#spring:
#  application:
#    name: microservice-foo300



#          http请求地址和资源文件映射如下:，可参考
#·        /{application}/{profile}[/{label}]
#
#·        /{application}-{profile}.yml
#
#·        /{label}/{application}-{profile}.yml
#
#·        /{application}-{profile}.properties
#
#·        /{label}/{application}-{profile}.properties

name: qpp
