server:
  port: 8050
spring:
  application:
    name: config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qipengpai/comic-cloud
          search-paths: config-repo
          username: 1074723451@qq.com
          password: pp210510.
#          force-pull，配置当本地目录与远程配置有冲突时是否强制拉取配置
#          代码很简单，即为标准的spring-boot项目启动代码
eureka:
#  instance:
#    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#    https://blog.csdn.net/red_sheeps/article/details/78386885