server:
  port: 8050
spring:
  application:
    name: config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qipengpai/comic-cloud
          search-paths: config-repo
          username: 1074723451@qq.com
          password: pp210510.
eureka:
#  instance:
#    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/