spring:
  application:
    name: discovery-cluster
#  security:
#      basic:
#        enabled: true # 开启基于HTTP basic的认证
#      user:
#        name: user  # 配置登录的账号是user
#        password: password123 #配置登录的密码是password123
server:
  port: 8761                    # 指定该Eureka实例的端口

eureka:
  instance:
    hostname: discovery         # 指定该Eureka实例的主机名
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://localhost:8762/eureka/


# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756

